services:
  postgres:
    container_name: sungwoo_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    container_name: sungwoo_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"